<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('Report Academic Year'); 
	echo $this->headTitle(''); 
	
?>	
<div style="width: 28cm;margin: 0 auto;">
<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'other','action'=>'rpt-academic-year')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<input dojoType="dijit.form.TextBox"   id="txtsearch" name="txtsearch" placeholder="Search....." value="<?php echo $this->search['txtsearch'];?>" type="text">
		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
</form>
</div>
	<div style="border: 1px dotted #000;background: #fff;width: 27cm;margin: 0 auto;min-height: 27cm;padding: 0.5cm;">
		<div id="divPrint">
							<table style="background:#fff; margin: 0 auto; width: 100%;">
								<tr style="font-size: 13px;">
									<td colspan="2"></td>
									<td align="right">
									</td>
								</tr>
								<tr>
									<td width="28%" >
										<img style="width: 155px;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br /><br />
									</td>
									<td width="44%" align="center">
										<strong​​ style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">របាយការណ៏  ឆ្នាំសិក្សា</strong><br />
										<strong></strong><br />
									</td>
									<td width="28%" align="right">
									</td>
								</tr>
<style>
	table tr th{
		border: 1px solid #000;	
	}
</style>
								<tr>
									<td colspan="3">
										<table cellpadding="5"​ style="margin:0 auto;width:100%;border1px solid #000; border-collapse: collapse;white-space: nowrap;"  border="1" >
											<tr style="font-size:11px; height: 20px;" align="center" >
												<th rowspan="2">No.</th>
												<th rowspan="2">Academic</th>
												<th rowspan="2">Generation</th>
												<th rowspan="2">Academic Start</th>
												<th rowspan="2">Duration</th>
												<th rowspan="2">Academic End</th>
												<th colspan="2">Quarter</th>
												<th colspan="2">Semester</th>
												<th colspan="2">Year</th>
												<th rowspan="2">Note</th>
											</tr>
											<tr style="font-size:11px; height: 20px;">
											
												<th>Start Date</th>
												<th>End Date</th>
												
												<th>Start Date</th>
												<th>End Date</th>
												
												<th>Start Date</th>
												<th>End Date</th>
												
											</tr>
										<?php $i=0; foreach ($this->rs AS $row) { $i++;?>
											<tr style="font-size:11px; height: 20px;" align="center" >
												<th ><?php echo $i;?></th>
												<th ><?php echo $row['academic'];?></th>
												<th ><?php echo $row['batch'];?></th>	
												<th ><?php echo date("d-M-Y",strtotime($row['study_start']));?></th>
												<th ><?php echo $row['duration'];?></th>
												<th ><?php echo date("d-M-Y",strtotime($row['study_end']));?></th>
												<th ><?php echo date("d-M-Y",strtotime($row['quarter_start']));?></th>
												<th ><?php echo date("d-M-Y",strtotime($row['quarter_end']));?></th>
												<th ><?php echo date("d-M-Y",strtotime($row['semester_start']));?></th>
												<th ><?php echo date("d-M-Y",strtotime($row['semester_end']));?></th>
												<th ><?php echo date("d-M-Y",strtotime($row['yearly_start']));?></th>
												<th ><?php echo date("d-M-Y",strtotime($row['yearly_end']));?></th>
												<th align="left"><?php echo $row['note'];?></th>
											</tr>
										<?php }?>	
										</table>	
									</td>
								</tr>
								<tr>
									<td colspan="3">&nbsp;</td>
								</tr>
								<tr>
									<td colspan="3">&nbsp;</td>
								</tr>
								<tr >
									<td align="center" width="25%">
										<span style="font-weight: bold;font-size: 14px;">Verified by</span>
									</td>
									<td  width="50%">
										&nbsp;
									</td>
									<td align="center"  width="25%">
										<span style="font-weight: bold;font-size: 14px;text-align: right;">Prepared by</span>
									</td>
								</tr>
							</table>
		</div>
	</div>