

  <style>
  ul.link-rpt li a {
	color: #3A3939;
    height: 50px;
  	width:180px;
    display: block;
    padding: 10px;
    background: #D6D6D6;
  	font-family: 'Kh Battambang','Khmer Battambang' !important;
  	text-align: center;
  	word-wrap: break-word;
  } 
    ul.link-rpt li {
	float:left; margin:10px;
    list-style: none;
    border:1px solid #B1B0AF;
    word-wrap: break-word;
    
  } 
  .dijitReset, .dijitInline  ,.dijitButton {
	width: 200px !important;
  }
  </style>
  <?php 
  
  $tr = Application_Form_FrmLanguages::getCurrentlanguage();
  $rpt_fee=$this->url(array('module'=>'allreport','controller'=>'fee','action'=>'rpt-fee'), null, true);
  $rpt_servicecharge=$this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rpt-service-charge'), null, true);
  $rpt_student_balance=$this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rptstudentbalance'), null, true);
  $rpt_tuitionfee=$this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rpt-fee'), null, true);
  $rpt_studentpayment=$this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rpt-studentpayment'), null, true);
  $rpt_studentpaymentdetail=$this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rpt-studentpaymentdetail'), null, true);
  $rpt_student_nearly_end_service=$this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rptstudentnearlyendservice'), null, true);
  $rpt_expect_income=$this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rptexpectincome'), null, true);
  $rpt_student_payment_late=$this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rptstudentpaymentlate'), null, true);
  
  $rpt_product_location=$this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rpt-product-location'), null, true);
  $rpt_purchaseall=$this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rpt-purchaseall'), null, true);
  $rpt_purchase=$this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rpt-purchase'), null, true);
  ?>
  <div style="background:#ccc; width: 100%;">
  	<ul class="link-rpt">
  		<li><a href="<?php echo $rpt_studentpayment;?>"><?php echo $tr->translate('STUDENT_SERVICE_PAYMENT_REPORT');?></a></li>
  		<li><a href="<?php echo $rpt_studentpaymentdetail;?>"><?php echo $tr->translate('STUDENT_SERVICE_PAYMENT_DETAIL_REPORT');?></a></li>
  		<li><a href="<?php echo $this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rpt-paymentdetailbytype'), null, true);?>"><?php echo $tr->translate('STUDENT_PAYMENT_SERVICE_BY_TYPE_REPORT');?></a></li>
  		<li><a href="<?php echo $rpt_student_balance;?>"><?php echo $tr->translate('STUDENT_BALANCE_REPORT');?></a></li>
  		<li><a href="<?php echo $rpt_expect_income;?>"><?php echo $tr->translate('EXPECT_INCOME_REPORT');?></a></li>
  		<li><a href="<?php echo $rpt_student_nearly_end_service;?>"><?php echo $tr->translate('STUDENT_NEARLY_END_SERVICE_REPORT');?></a></li>
  		<li><a href="<?php echo $rpt_student_payment_late;?>"><?php echo $tr->translate('RPT_STUDENT_PAYMENT_LATE');?></a></li>
  		<li><a href="<?php echo $this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rpt-suspendservice'), null, true);?>"><?php echo $tr->translate('STUDENT_STOP_SERVICE_REPORT');?></a></li>
  		<li><a href="<?php echo $rpt_tuitionfee;?>"><?php echo $tr->translate('RPT_FEE');?></a></li>
  		<li><a href="<?php echo $rpt_servicecharge;?>"><?php echo $tr->translate('SERVICE_CHARGE_RPT');?></a></li>
  	   
  	   <li><a href="<?php echo $rpt_product_location;?>"><?php echo $tr->translate('RPT_PRODUCT_LOCATION');?></a></li>
  		<li><a href="<?php echo $rpt_purchaseall;?>"><?php echo $tr->translate('RPT_PURCHASE_ALL');?></a></li>
  		<li><a href="<?php echo $rpt_purchase;?>"><?php echo $tr->translate('RPT_PURCHASE');?></a></li>  	
  	
  	</ul>
  </div>
  <div style="clear: both;"></div>
  
  
  
  
  
  
  