<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('SRMS | Report Student Receivable'); 
	echo $this->headTitle();
	$base_url = Application_Form_FrmMessage::getUrl("/");
?>
<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rpt-studentpayment')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<input  dojoType="dijit.form.TextBox"   id="txtsearch" name="txtsearch" placeholder="Advance Search....." value="<?php echo $this->search['txtsearch'];?>" type="text">
		<input  name="from_date" id="from_date" dojoType="dijit.form.DateTextBox"  value="<?php echo $this->search['start_date'];?>" type="text">
		<input  name="to_date" id="to_date" dojoType="dijit.form.DateTextBox"  value="<?php echo $this->search['end_date'];?>" type="text">
		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
</form>
<style>
#footer{display: none;}
</style>	
<div style="border: 1px dotted #000;background: #fff; margin: 0 auto;min-height: 27cm;">
		<div id="divPrint">
			<table style="background:#fff; margin: 0 auto; width: 100%; padding: 1cm; ">
							<tr>
									<td>&nbsp;</td>
							</tr>
							<tr>
								<td width="20%" align="left">
									<img style="width: 80%;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br /><br />
								</td>
								<td align="center" width="60%">
									<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';"><?php echo $tr->translate('STUDENT_SERVICE_PAYMENT_REPORT');?></strong><br >
								</td>
								<td align="right" width="20%">&nbsp;</td>
							</tr>
							<tr> 
								<td colspan="3" id="exportExcel" >
									<style> th,td{ padding:0 1px;}</style>
										<style type="text/css">
											body{font-family: "Times New Roman",Arial; }
											table{ border-collapse:collapse; margin:0 auto;
											border-color:#000; }
											.padd tr td{  text-align:center}
											.padd tr th{  background-color: #ccc; }
										</style>

									<table class="padd" width="99%" border="1" align="center" style="white-space:nowrap;font-family: 'Hanuman';">
										  <tr style="font-size:12px; height: 20px;background-color: #ccc;line-height: 30px;font-weight: bold;" align="center">
										    <td>&nbsp;<?php echo $tr->translate('N_O');?>&nbsp;</td>
										    <td>&nbsp;<?php echo $tr->translate('STUDENT_ID');?>&nbsp;</td>
											<td>&nbsp;<?php echo $tr->translate('NAME_KH');?>&nbsp;</td>
											<td>&nbsp;<?php echo $tr->translate('NAME_EN');?>&nbsp;</td>
											<td>&nbsp;<?php echo $tr->translate('RECEIPT_NO');?>&nbsp;</td>
											<td>&nbsp;<?php echo $tr->translate('TUITION_FEE');?>&nbsp;</td>
											<td>&nbsp;<?php echo $tr->translate('DISCOUND');?>&nbsp;</td>
											<td>&nbsp;<?php echo $tr->translate('SUBTOTAL');?>&nbsp;</td>
											<td>&nbsp;<?php echo $tr->translate('PAID_AMOUNT');?>&nbsp;</td>
											<td>&nbsp;<?php echo $tr->translate('RECEIVED_AMOUNT');?>&nbsp;</td>
											<td>&nbsp;<?php echo $tr->translate('BALANCE');?>&nbsp;</td>
											<td>&nbsp;<?php echo $tr->translate('RETURN');?>&nbsp;</td>
											<td>&nbsp;<?php echo $tr->translate('PAID_DATE');?>&nbsp;</td>
											<td>&nbsp;<?php echo $tr->translate('USER');?>&nbsp;</td>
											<td>&nbsp;<?php echo $tr->translate('REMARK');?>&nbsp;</td>
										  </tr>
										  <tr></tr>
												<style> td{padding:0 3px; }</style>
										 <?php $i=0; $total=0;$paid=0;$balance=0;$receive_amount=-0;$return_amount=0; if (!empty($this->row)) { foreach($this->row as $rs){ $i++;?>
										  <tr class="hover" style="font-size:11px; height: 18px;"​ align="center">
										    <td><?php echo $i;?></td>
										    <td><a style=" text-decoration: none; color:#000;" href="<?php echo $this->url(array('controller'=>'accounting','action'=>'rpt-paymentrecieptdetail','id'=>$rs['id']));?>" target="blank"><?php echo $rs['stu_code']; ?></a></td>
										    <td style=" white-space:nowrap; text-align:left"><a style=" text-decoration: none; color:#000;" href="<?php echo $this->url(array('controller'=>'accounting','action'=>'rpt-paymentrecieptdetail','id'=>$rs['id']));?>" target="blank"><?php echo $rs['kh_name']; ?></a></td>
										    <td style=" white-space:nowrap; text-align:left"><a style=" text-decoration: none; color:#000;" href="<?php echo $this->url(array('controller'=>'accounting','action'=>'rpt-paymentrecieptdetail','id'=>$rs['id']));?>" target="blank"><?php echo $rs['en_name']; ?></a></td>
										    <td><a style=" text-decoration: none; color:#000;" href="<?php echo $this->url(array('controller'=>'accounting','action'=>'rpt-paymentrecieptdetail','id'=>$rs['id']));?>" target="blank"><?php echo $rs['receipt_number']; ?></a></td>
										    <td>$ <?php echo $rs['tuition_fee']; if(empty($rs['tuition_fee'])){} ?></td>
										    <td> <?php echo $rs['discount_percent']; ?></td>
										    <td>$ <?php echo $rs['total'];?></td>
										    <td>$ <?php echo $rs['paid_amount'];?></td>
										    <td>$ <?php echo $rs['receive_amount'];?></td>
										    <td>$ <?php echo $rs['balance_due'];?></td>
										    <td>$ <?php echo $rs['return_amount']; if(empty($rs['return_amount']))echo '0'; ?></td>
										    <td><?php echo date('d-M-Y', strtotime($rs['create_date'])); ?></td>
										    <td><?php echo $rs['USER']; ?></td>
										   	<td><?php echo $rs['note']; ?></td>
										  </tr>
										  <?php 
										  		$total = $rs['total'] + $total; 
										  		$paid = $rs['paid_amount'] + $paid;
										  		$balance = $rs['balance_due'] + $balance;
										  		$receive_amount = $rs['receive_amount'] + $receive_amount;
										  		$return_amount = $rs['return_amount'] + $return_amount;
										  ?> 
										  <?php }} ?>
										</table>
									
									</td>
								</tr>
									<tr><td colspan="3">&nbsp;</td></tr>
								<tr>
									<td colspan="3">&nbsp;</td>
								</tr>
								<?php if(!empty($total)){?>
								<tr>
									<td colspan="3">
											<table width="29.2%" border="1" align="right" style="margin-right:0.1%; white-space:nowrap;">
												<tr style="font-size:10px; color:#000; height: 23px;"​ align="center">
										 				<th style="background-color: #ccc; width: 38%; font-weight:bold;font-family: Arial Black; font-size: 10px;">&nbsp;<?php echo $tr->translate('GRAND_TOTAL');?>&nbsp;</th>
														<td colspan="2" style=" font-weight:bold;font-family: Arial Black; font-size: 10px;"><span style="color: red;">$ <?php echo number_format($total,2);?></span></td>
										  		</tr>
										  		<tr style="font-size:10px; color:#000; height: 23px;"​ align="center">
										 				<th style="background-color: #ccc; width: 38%; font-weight:bold;font-family: Arial Black; font-size: 10px;">&nbsp;<?php echo $tr->translate('GRAND_TOTAL_PAID_AMOUNT');?>&nbsp;</th>
														<td colspan="2" style=" font-weight:bold;font-family: Arial Black; font-size: 10px;"><span style="color: red;">$ <?php echo number_format($paid,2);?></span></td>
										  		</tr>
										  		<tr style="font-size:10px; color:#000; height: 23px;"​ align="center">
										 				<th style="background-color: #ccc; width: 38%; font-weight:bold;font-family: Arial Black; font-size: 10px;">&nbsp;<?php echo $tr->translate('GRAND_TOTAL_RECEIVED_AMOUNT');?>&nbsp;</th>
														<td colspan="2" style=" font-weight:bold;font-family: Arial Black; font-size: 10px;"><span style="color: red;">$ <?php echo number_format($receive_amount,2);?></span></td>
										  		</tr>
										  		<tr style="font-size:10px; color:#000; height: 23px;"​ align="center">
										 				<th style="background-color: #ccc; width: 38%; font-weight:bold;font-family: Arial Black; font-size: 10px;">&nbsp;<?php echo $tr->translate('GRAND_TOTAL_BALANCE');?>&nbsp;</th>
														<td colspan="2" style=" font-weight:bold;font-family: Arial Black; font-size: 10px;"> <span style="color: red;">$ <?php echo number_format($balance,2);?></span></td>
										  		</tr>
										  		<tr style="font-size:10px; color:#000; height: 23px;"​ align="center">
										 				<th style="background-color: #ccc; width: 38%; font-weight:bold;font-family: Arial Black; font-size: 10px;">&nbsp;<?php echo $tr->translate('GRAND_TOTAL_RETURN');?>&nbsp;</th>
														<td colspan="2" style=" font-weight:bold;font-family: Arial Black; font-size: 10px;"><span style="color: red;">$ <?php echo number_format($return_amount,2);?></span></td>
										  		</tr>
										  </table>
									</td>
								</tr>
								<tr>
											<td colspan="3">&nbsp;</td>
										</tr>
										<tr>
											<td colspan="3">&nbsp;</td>
										</tr>
										<tr >
											<td align="center" width="25%">
												<span style=" font-size: 14px;"><?php echo $tr->translate('VERIFIED_BY');?></span>
											</td>
											<td  width="50%">
												&nbsp;
											</td>
											<td align="center"  width="25%">
												<span style=" font-size: 14px;text-align: right;"><?php echo $tr->translate('PREPARE_BY');?></span>
											</td>
										</tr>
								<?php  }?>
							</table>
	</div>	
</div>

