<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('Report Student Balance'); 
	echo $this->headTitle(''); 
	
?>	
<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rpt-student-service-payment')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		
		
		<select dojoType="dijit.form.FilteringSelect"   id="searchby" name="searchby" placeholder="Search by ....." value="" type="text">
			<option value="0">All</option>
			<option value="1">Academic Year</option>
			<option value="2">Code</option>
			<option value="3">Student Name</option>
			<option value="4">Note</option>
		</select>
		<input dojoType="dijit.form.TextBox"  id="txtsearch" name="txtsearch" placeholder="Search....." value="" type="text">
		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
</form>		
<div style="border: 1px dotted #000;background: #fff;width: 26cm;margin: 0 auto;min-height: 27cm;">
			<div id="divPrint">
				
									<table style="background:#fff; margin: 0 auto; padding: 1cm;">
										
										<tr>
											<td width="28%" align="left">
												<img style="width:70%;" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br /><br >
											</td>
											<td align="center" width="44%">
												<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">របាយការណ៏​​ សិស្សមិន​ទាន់បានបង់ថ្លៃសេវាកម្ម</strong><br /><br >
											</td>
											<td width="28%" align="right">
												<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">ក្រសួងអប់រំ យុវជន និងកីឡា</strong><br />
												<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';margin-right: 25px;">សាលា អាស៊ាន ហ៊ែរីថេជ</strong><br /><br >
											</td>
										</tr>
										<tr>
											<td colspan="3">
												<table cellpadding="5"​ style="margin:0 auto;border: 1px solid #000;width:100%; border-collapse: collapse;white-space: nowrap;"  border="1" >
													<tr style="font-size:11px; height: 20px;border: 1px solid #000;" align="center" >
														<th style="border: 1px solid #000;">&nbsp;ល.រ&nbsp;</th>
														<th style="border: 1px solid #000;">&nbsp;Academic Year&nbsp;</th>
														<th style="border: 1px solid #000;">Code</th>
														<th style="border: 1px solid #000;">&nbsp;Student Name&nbsp;</th>
														<th style="border: 1px solid #000;">&nbsp;Sex&nbsp;</th>
														<th style="border: 1px solid #000;">Service Name</th>
														<th style="border: 1px solid #000;">Total</th>
														<th style="border: 1px solid #000;">&nbsp;Discount&nbsp;</th>
														<th style="border: 1px solid #000;">&nbsp;Total Payment&nbsp;</th>
														<th style="border: 1px solid #000;">&nbsp;Paid Amount&nbsp;</th>
														<th style="border: 1px solid #000;">&nbsp;Balance&nbsp;</th>
														<th style="border: 1px solid #000;">Validate</th>
														<th style="border: 1px solid #000;">Note</th>
														
													</tr>
												<?php $i=0; foreach ($this->rs AS $row) { $i++;?>
													<tr style="font-size:10px; height: 20px;border: 1px solid #000;" align="center" >
														<th style="border: 1px solid #000;"><?php echo $i;?></th>
														<th style="border: 1px solid #000;"><?php echo $row['year'];?></th>
														<th style="border: 1px solid #000;">&nbsp;<?php echo $row['code'];?>&nbsp;</th>
														<th align="left" style="border: 1px solid #000;">&nbsp;<?php echo $row['name'];?></th>	
														<th style="border: 1px solid #000;"><?php echo $row['sex'];?></th>
														<th align="left" style="border: 1px solid #000;">&nbsp;<?php echo $row['service'];?></th>
														<th style="border: 1px solid #000;">&nbsp;<?php echo $row['fee'];?>&nbsp;</th>
														<th style="border: 1px solid #000;"><?php echo $row['discount'];?></th>
														<th style="border: 1px solid #000;"><?php echo $row['payment'];?></th>
														<th style="border: 1px solid #000;"><?php echo $row['paid'];?></th>
														<?php if($row['complete']==0){ ?>
															<th style="border: 1px solid #000;color:red;"><?php echo $row['balance'];?></th>
														<?php }else{?>
															<th style="border: 1px solid #000;"><?php echo $row['balance'];?></th>
														<?php }?>
														<th style="border: 1px solid #000;">&nbsp;<?php echo $row['validate'];?>&nbsp;</th>
														<?php if($row['complete']!=0){ ?>
															<th style="border: 1px solid #000;">&nbsp;<?php echo $row['comment'];?>&nbsp;</th>
														<?php }else{?>
															<th style="border: 1px solid #000;color:red;">&nbsp;<?php echo $row['comment'];?>&nbsp;</th>
														<?php }?>
													</tr>
												<?php }?>	
												</table>	
											</td>
										</tr>
									</table>
							
			</div>		
</div>