<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('Report Service Charge'); 
	echo $this->headTitle(''); 
	
?>	
<div style="width: 28cm;margin: 0 auto;">
<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rpt-service-charge')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<table>	
		<tr>
			<td>
				<input dojoType="dijit.form.TextBox" id="txtsearch" name="txtsearch" placeholder="Search....." value="<?php echo $this->search['txtsearch'];?>" type="text">
			</td>
			<td>
				<select class="fullside"   name="year" id="year" dojoType="dijit.form.FilteringSelect">
					<option value=""> Select Year </option>
					<?php if(!empty($this->row)){foreach ($this->row as $id ){?>
						<option value="<?php echo $id['id']?>" <?php if($id['id']==$this->search['year']) echo 'selected="selected"' ?>><?php echo $id['year'];?></option>
					<?php }}?>
				</select>
			</td>
			<td>
				<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
			</td>
		</tr>
	
	
	</table>
</form>	
</div>
<div style="border: 1px dotted #000; background: #fff;width: 27cm;margin: 0 auto;min-height: 27cm;padding: 0.5cm;">
	<div id="divPrint">
							<table style="background:#fff; margin: 0 auto; white-space: nowrap;width: 100%">
										<tr >
											<td width="25%" align="left">
												<img style="width: 80%;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br /><br >
											</td>
											<td width="50%"  align="center">
												<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 16px;font-family:'Khmer MEF2';"><?php echo $tr->translate('SERVICE_CHARGE_RPT');?></strong><br /><br >
											</td>
											<td width="25%" align="right">
											</td>
										</tr>
										

								<tr>
									<td colspan="3" id="exportExcel">
										<table cellpadding="5"​ style="margin:0 auto;width:100%;border: 1px solid #000; border-collapse: collapse;border: 1px solid #000;white-space: nowrap;"  border="1" >
											<tr style="font-size:11px;background-color: #ccc;line-height: 30px;font-weight: bold;" align="center" >
												<td ><?php echo $tr->translate('N_O')?></td>
												<td ><?php echo $tr->translate('ACADEMIC_YEAR')?></td>
												<td ><?php echo $tr->translate('GENERATION')?></td>
												<td><?php echo $tr->translate('SERVICE_NAME')?></td>
												<td><?php echo $tr->translate('MONTHLY')?></td>
												<td ><?php echo $tr->translate('QUARTER')?></td>
												<td ><?php echo $tr->translate('SEMESTER')?></td>
												<td ><?php echo $tr->translate('YEAR')?></td>
												<td ><?php echo $tr->translate('NOTE')?></td>
											</tr>
										<?php $i=0; foreach ($this->rs AS $row) { $i++;?>
											<tr class="hover" style="font-size:11px; height: 20px;" align="center" >
												<td ><?php echo $i;?></td>
												<td ><?php echo $row['academic'];?></td>
												<td ><?php echo $row['generation'];?></td>
												<td align="left">&nbsp;&nbsp;<?php echo $row['service_name'];?></td>	
												<td ><?php echo $row['monthly'];?></td>
												<td ><?php echo $row['quarter'];?></td>
												<td ><?php echo $row['semester'];?></td>
												<td ><?php echo $row['year'];?></td>
												<td ><?php echo $row['remark'];?></td>
											</tr>
										<?php }?>	
										</table>	
									</td>
								</tr>
								<tr>
									<td colspan="3">&nbsp;</td>
								</tr>
								<tr>
									<td colspan="3">&nbsp;</td>
								</tr>
								<tr >
									<td align="center" width="25%">
										<span style="font-weight: bold;font-size: 14px;"><?php echo $tr->translate('VERIFIED_BY');?></span>
									</td>
									<td  width="50%">
										&nbsp;
									</td>
									<td align="center"  width="25%">
										<span style="font-weight: bold;font-size: 14px;text-align: right;"><?php echo $tr->translate('PREPARE_BY');?></span>
									</td>
								</tr>
							</table>
	</div>	
</div>	
