<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('SRMS | Report Student Receivable'); 
	echo $this->headTitle();
	$base_url = Application_Form_FrmMessage::getUrl("/");
?>
<style>
#footer{display: none;}
</style>	
<div style="border: 1px dotted #000;background: #fff; margin: 0 auto;min-height: 27cm;">
		<div id="divPrint">
			<table style="background:#fff; margin: 0 auto; width: 100%; padding: 1cm; ">
							<tr style="font-size: 13px;">
								<td colspan="3" align="center">
									<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">ព្រះរាជាណាចក្រកម្ពុជា</strong><br />
									<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">ជាតិ សាសនា ព្រះមហាក្សត្រ</strong><br />
								</td>
							</tr>
							<tr>
									<td>&nbsp;</td>
							</tr>
							<tr>
								<td width="20%" align="left">
									<img style="width: 155px;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br /><br />
								</td>
								<td align="center">
									<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';"><u>ពត៌មានលំអិត សិស្សដែលផ្អាកសេវាកម្ម</u></strong><br >
								</td>
								<td align="right" width="20%">
									<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">ក្រសួងអប់រំ យុវជន និងកីឡា</strong><br />
									<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';margin-right: 25px;">សាលា អាស៊ាន ហ៊ែរីថេជ</strong><br /><br >
								</td>
							</tr>
							<tr>
								<td colspan="3">
									<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">Student ID : <?php echo $this->rr['student_id'];?> <br />Name : <?php echo $this->rr['name_en'];?><br /> Gender : <?php echo $this->rr['sex']; ?></strong></td>
							</tr>
							<tr>
								<td colspan="3">
									<style> th,td{ padding:0 1px;}</style>
										<style type="text/css">
											body{font-family: "Times New Roman",Arial; }
											table{ border-collapse:collapse; margin:0 auto;
											border-color:#000; }
											.padd tr td{  text-align:center}
											.padd tr th{  background-color: #ccc; }
										</style>

									<table class="padd" width="99%" border="1" align="center" style="white-space:nowrap;">
										  <tr style="font-size:10px; height: 30px;" align="center">
										    <th>&nbsp;N.o&nbsp;</th>
										    <th>&nbsp;Suspend N.o&nbsp;</th>
											<th>&nbsp;Service&nbsp;</th>
											<th>&nbsp;Payterm&nbsp;</th>
											<th>&nbsp;Type Suspend&nbsp;</th>
											<th>&nbsp;Reason&nbsp;</th>
											<th>&nbsp;Note&nbsp;</th>
											<th>&nbsp;Date&nbsp;</th>
										  </tr>
										  <tr></tr>
												<style> td{padding:0 3px; }</style>
										  <?php $i=0; $total=0;if (!empty($this->rs)) foreach($this->rs as $rs){ $i++;?>
										  <tr style="font-size:10px; height: 23px;"​ align="center">
										  	<td><?php echo $i;?></td>
										   	<td><?php echo $rs['suspend_no']; ?></td>
										   	<td><?php echo $rs['service']; ?></td>
										  	<td><?php echo $rs['payment_term']; ?></td>
										  	<td><?php echo $rs['type_suspend']; ?></td>
										   	<td><?php echo $rs['reason']; ?></td>
										   	<td><?php echo $rs['note']; ?></td>
										   	<td><?php echo $rs['define_date']; ?></td>
										  </tr>
										  <?php } ?>
										</table>
									
									</td>
								</tr>
							</table>
	</div>	
</div>

