<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('Report Student Late'); 
	echo $this->headTitle(''); 
	
?>	
<?php
// 			$date1=date_create("2013-03-15");
// 			$date2=date_create("2013-04-15");
// 			$diff=date_diff($date1,$date2);
// 			echo $diff->format("%R%a days");exit();
?>
<div style="width: 27cm;margin: 0 auto;">
<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'rptstudentlate')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<table>	
		<tr>
			<td>
				<input dojoType="dijit.form.TextBox" id="txtsearch" name="txtsearch" placeholder="Search....." value="" type="text">
			</td>
			<td>
				<input class="fullside" name="from_date" id="from_date" dojoType="dijit.form.DateTextBox" placeholder="from date" value="<?php echo $this->search['start_date'];?>" type="text">
			</td>
			<td>
				<input class="fullside" name="to_date" id="to_date" dojoType="dijit.form.DateTextBox" placeholder="to date" value="<?php echo $this->search['end_date'];?>" type="text">
			</td>
			<td>
				<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
			</td>
		</tr>
	</table>
</form>	
</div>
<div style="border: 1px dotted #000;background: #fff;width: 27cm;margin: 0 auto;min-height: 27cm;">
	<div id="divPrint">
									<table style="background:#fff;width:90%; margin: 0 auto; padding: 0.5cm;">
										
										<tr>
											<td width="28%" align="left">
												<img style="width:70%;" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br /><br >
											</td>
											<td align="center" width="44%">
												<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">របាយការណ៏​​ សិស្សយឺត</strong><br /><br >
											</td>
											<td width="28%" align="right">
											</td>
										</tr>
										<tr>
											<td colspan="3">
												<table cellpadding="5"​ style="margin:0 auto;border: 1px solid #000;width:100%; border-collapse: collapse;white-space: nowrap;"  border="1" >
													<tr style="font-size:11px; height: 20px;border: 1px solid #000;" align="center" >
														<th style="border: 1px solid #000;">&nbsp;N.o&nbsp;</th>
														<th style="border: 1px solid #000;">&nbsp;Receipt No&nbsp;</th>
														<th style="border: 1px solid #000;">Code</th>
														<th style="border: 1px solid #000;">&nbsp;Student Name&nbsp;</th>
														<th style="border: 1px solid #000;">&nbsp;Sex&nbsp;</th>
														<th style="border: 1px solid #000;">Service Name</th>
														<th style="border: 1px solid #000;">Paid Date</th>
														<th style="border: 1px solid #000;">Validate</th>
														<th style="border: 1px solid #000;">Remain Date</th>
														
													</tr>
												<?php $i=0;$totalpaid=0;$totalbalance=0; if(!empty($this->row)){foreach ($this->row AS $row) { $i++;
												
													$date1=date_create($row['end']);
													$date2=date_create(date('Y-m-d'));
													$diff=date_diff($date1,$date2);
													$day=$diff->format("%R%a");
// 													echo $diff->format('%R'); // use for point out relation: smaller/greater
// 													echo $diff->days;
												?>
													<tr style="font-size:10px; height: 20px;border: 1px solid #000;" align="center" >
														<th style="border: 1px solid #000;"><?php echo $i;?></th>
														<th style="border: 1px solid #000;"><?php echo $row['receipt'];?></th>
														<th style="border: 1px solid #000;">&nbsp;<?php echo $row['code'];?>&nbsp;</th>
														<th align="left" style="border: 1px solid #000;">&nbsp;<?php echo $row['name'];?></th>	
														<th align="left" style="border: 1px solid #000;">&nbsp;<?php echo $row['sex'];?></th>
														<th align="left" style="border: 1px solid #000;">&nbsp;<?php echo $row['service'];?></th>
														<th style="border: 1px solid #000;">&nbsp;<?php echo date("d-M-Y",strtotime($row['start']));?>&nbsp;</th>
														<th style="border: 1px solid #000;color: red;">&nbsp;<?php echo date("d-M-Y",strtotime($row['end']));?>&nbsp;</th>
														<th align="center" style="border: 1px solid #000;color: red;">&nbsp;<?php echo abs($day);?></th>
 													</tr>
												<?php }}?>	 
												</table>	
											</td>
										</tr>
										
										<tr>
											<td colspan="3">&nbsp;</td>
										</tr>
										<?php //if (empty($total_fee)){}?>
										<?php ///if (!empty($total_fee)){?>
									<!--	<tr>
											<td colspan="2"></td>
											<td>
												<table border="1" align="right" style="width:50%; margin-right:0.5%; white-space:nowrap;border-collapse: collapse;border: 1px #000 solid;">
													<tr style="font-size:10px; background:#ccc; height: 20px;width: 400px;" align="center">
														<th>&nbsp;Total Balance Paid &nbsp;</th>
														<th>&nbsp;Total Balance Remain&nbsp;</th>
													</tr>
													<tr align="center" style=" height:18px; font-size:10px; padding: 1px;font-weight: bold;" >
														<td>$ <?php echo number_format($totalpaid,2);?></td>
														<td style="color: red;">$ <?php echo number_format($totalbalance,2);?></td>
													</tr>
												  </table>
											</td>
										</tr>-->
										<?php //}?>
									</table>
							
			</div>		
</div>





