<?php 
	  $tr=Application_Form_FrmLanguages::getCurrentlanguage();
	
	  $home=$this->url(array('module'=>'home','controller'=>'index','action'=>'index'), null, true);
	  $sale=$this->url(array('module'=>'sale','controller'=>'index','action'=>'index'), null, true);
	  $foundation=$this->url(array('module'=>'foundation','controller'=>'register','action'=>'index'), null, true);
	  $product=$this->url(array('module'=>'product','controller'=>'index','action'=>'index'), null, true);
	  $accounting=$this->url(array('module'=>'accounting','controller'=>'fee','action'=>'index'), null, true);
	 // $gep=$this->url(array('module'=>'gep','controller'=>'studentstudy','action'=>'index'), null, true);
	  //$gep=$this->url(array('module'=>'gep','controller'=>'gep','action'=>'index'), null, true);
	  $report=$this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'index'), null, true);
	  $purchase=$this->url(array('module'=>'purchase','controller'=>'index','action'=>'index'), null, true);
	  $kidergarten=$this->url(array('module'=>'kindergarten','controller'=>'kindergarten','action'=>'index'), null, true);
	  $reference_path=$this->url(array('module'=>'analysis','controller'=>'query','action'=>'index'), null, true);
	  $backup=$this->url(array('module'=>'backup','controller'=>'index','action'=>'index'), null, true);
      $user=$this->url(array('module'=>'user','controller'=>'index','action'=>'index'), null, true);
      $acl=$this->url(array('module'=>'rsvacl','controller'=>'index','action'=>'index'), null, true);
      $setting=$this->url(array('module'=>'setting','controller'=>'index','action'=>'index'), null, true);
       
      $module=Zend_Controller_Front::getInstance()->getRequest()->getModuleName();
	  
	  $session_user=new Zend_Session_Namespace('auth');
	  $level=$session_user->level;
	  $item_arr=array(
	   'index'=>'<li class="link">
							<a title="ទំព័រដើម" href="'.$home.'">
								<span>'.$tr->translate("HOME_PAGE").'</span>
							</a>
						</li>',	  
	  'sale'=>'<li class="link">
						<a title="ការិ.ចុះឈ្មោះ" href="'.$sale.'">
							<span>'.$tr->translate("SALES").'</span>
						</a>
				  </li>',
	  'product'=>'<li class="link">
	  		<a title="ព័ត៏មានផ្សេងៗ" href="'.$product.'">
	  		<span>'.$tr->translate("PURODUCT").'</span>
	  		</a>
	  		</li>',
	  'purchase'=>'<li class="link">
	  		<a title="ការិយាល័យរដ្ឋបាល" href="'.$purchase.'">
	  		<span>'.$tr->translate("PURCHASE").'</span>
	  		</a>
	  		</li>',
	     
	    'allreport'=>'<li class="link">
						<a title="របាយការណ៏" href="'.$report.'">
							<span>'.$tr->translate("REPORT").'</span>
						</a>
					   </li>',
		
	  	'rsvacl'=>'<li class="link">
				  		<a title="acl" href="'.$acl.'">
				  		<span>'.$tr->translate("ACL").'</span>
				  		</a>
				  		</li>',
	 
	  );
?>  
<div id="menu">
	<ul>
		<?php
			foreach($item_arr as $key=>$value){
				if($module==$key){
					echo str_replace('class="link"', 'class="current"', $value);
				}
				else{
					echo $value;
				}
			} 
		?>
		<li style="float: right;">
			<a href="" class="langiconen" onclick="changeLange(2);"></a>
		</li>
		<li style="float: right;  border-left: 1px solid #fff; border-right: 1px solid #fff;">
		<a href="" class="langiconkh" onclick="changeLange(1);"></a>
		</li>
	</ul>
</div>

<script>	
var url_changelang = '<?php echo $this->url(array('module'=>'default','controller'=>'index','action'=>'changelange'));?> ';
function changeLange(lang){
	dojo.xhrPost({
		url: url_changelang,
	    content :{ 
			    'lange':lang,
		},	
		handleAs:"json",
		load: function(data) {
			location.reload();
		},
		error: function(err) {
			
		}
	});
}
	</script>