	<?php
	$request=Zend_Controller_Front::getInstance()->getRequest();
	$action = $request->getActionName();
	$baseurl  = $this->baseUrl();
	$other=$acl=$this->url(array('module'=>'allreport','controller'=>'other','action'=>'index'), null, true);
	$registrar=$acl=$this->url(array('module'=>'allreport','controller'=>'receiptionist','action'=>'index'), null, true);
	$accoutning=$acl=$this->url(array('module'=>'allreport','controller'=>'accounting','action'=>'index'), null, true);
	$fundation=$acl=$this->url(array('module'=>'allreport','controller'=>'foundation','action'=>'index'), null, true);
	$allstudent=$acl=$this->url(array('module'=>'allreport','controller'=>'allstudent','action'=>'index'), null, true);
	
	//$allstudent=$acl=$this->url(array('module'=>'allreport','controller'=>'allstudent','action'=>'index'), null, true);
	
	/*--------------------URLs link display--------------------------*/
		  $tr=Application_Form_FrmLanguages::getCurrentlanguage();
		$arr_param_menu=array( 
			'home'=>array(
						
			),
			'default'=>array(
					),
			'registrar'=>array(
			    /*'index'=>'<li><a href="">'.$tr->translate("RECEIPT").'</a></li>',
			     * 'request'=>'<li><a href="">'.$tr->translate("STUDENT_REQUEST").'</a></li>',		*/
			    'register'=>'<li><a href="">'.$tr->translate("STUDENT_REGISTRATION").'</a></li>',
				//'coursestudy'=>'<li><a href="">'.$tr->translate("STUDENT_COURSE").'</a></li>',
				//'studentservicepayment'=>'<li><a href="">'.$tr->translate("STUDENT_SERVICE_PAYMENT").'</a></li>',
				//'uniformandbook'=>'<li><a href="">'.$tr->translate("UNIFORM_AND_BOOK_PAYMENT").'</a></li>',
				/*'gepregister'=>'<li><a href="">'.$tr->translate("ចុះឈ្មោះបង់លុយ(TC)").'</a></li>',*/
				'income'=>'<li><a href="">'.$tr->translate("OTHER_INCOME").'</a></li>',
				'expense'=>'<li><a href="">'.$tr->translate("OTHER_EXPENSE").'</a></li>',
				'calculator'=>'<li><a href="">'.$tr->translate("CALCULATE_LIST").'</a></li>',
				'allreports'=>'<li><a href="">'.$tr->translate("RPT_CASHPAYMENT").'</a></li>',
				'studentnearlyendservice'=>'<li><a href="">'.$tr->translate("STUDENT_NEARLY_END_SERVICE").'</a></li>',
				'studentpaymentlate'=>'<li><a href="">'.$tr->translate("STUDENT_PAYMENT_LATE").'</a></li>',
			),
			'product'=>array(
						//'group'=>'<li><a href="">'.$tr->translate("STUDY_GROUP").'</a></li>',
						//'academicyear'=>'<li><a href="">'.$tr->translate("ACADEMIC_YEAR").'</a></li>',
						//'subject'=>'<li><a href="">'.$tr->translate("SUBJECT").'</a></li>',
						'index'=>'<li><a href="">'.$tr->translate("PRODUCT").'</a></li>',
						'category'=>'<li><a href="">'.$tr->translate("CATEGORY").'</a></li>',
						//'situation'=>'<li><a href="">'.$tr->translate("SITUATIONS").'</a></li>',
					    'occupation'=>'<li><a href="">'.$tr->translate("OCCUPATION").'</a></li>',
						'province'=>'<li><a href="">'.$tr->translate("CITY_PROVINCE").'</a></li>',
						//'highschool'=>'<li><a href="">'.$tr->translate("HIGHSCHOOL").'</a></li>',
						//'icon'=>'<li><a href="">'.$tr->translate("ICON").'</a></li>',
				),
			'sale'=>array(
				'register'=>'<li><a href="">'.$tr->translate("REGISTER").'</a></li>',
				//'gep'=>'<li><a href="">'.$tr->translate("GEP_REGISTER").'</a></li>',
				'faculty'=>'<li><a href="">'.$tr->translate("DEGREE").'</a></li>',
				'major'=>'<li><a href="">'.$tr->translate("GRADE").'</a></li>',
				'language'=>'<li><a href="">'.$tr->translate("DEGREE_LANGUAGE").'</a></li>',
 
			),
			'kindergarten'=>array(
						//'studentgroup'=>'<li><a href="">'.$tr->translate("STUDENT_GROUP").'</a></li>',
						'kindergarten'=>'<li><a href="">'.$tr->translate("KINDERGARTEN_REGISTER").'</a></li>',
						'studentgroup'=>'<li><a href="">'.$tr->translate("STUDENT_GROUP").'</a></li>',
						'studentchangegroup'=>'<li><a href="">'.$tr->translate("STUDENT_CHANGE_GROUP").'</a></li>',
						'groupstudentchangegroup'=>'<li><a href="">'.$tr->translate("GROUP_STUDENT_CHANGE_GROUP").'</a></li>',
						'studentdrop'=>'<li><a href="">'.$tr->translate("STUDENT_DROP").'</a></li>',
						'attendent'=>'<li><a href="">'.$tr->translate("ATTENDENT").'</a></li>',
						//'studentstudy'=>'<li><a href="">'.$tr->translate("STUDENT_STUDY").'</a></li>',
						//'student'=>'<li><a href="">'.$tr->translate("STUDENT_LIST").'</a></li>',
						'attendent'=>'<li><a href="">'.$tr->translate("ATTENDENT").'</a></li>',
						'language'=>'<li><a href="">'.$tr->translate("DEGREE_LANGUAGE").'</a></li>',
					    'studentscores'=>'<li><a href="">'.$tr->translate("STUDENT_SCORE").'</a></li>',
				
				
				),
				'gep'=>array(

						//'studentgroup'=>'<li><a href="">'.$tr->translate("STUDENT_GROUP").'</a></li>',
						//'register'=>'<li><a href="">'.$tr->translate("KINDERGARTEN_REGISTER").'</a></li>',

						//'studentstudy'=>'<li><a href="">'.$tr->translate("REGISTER").'</a></li>',
						//'gep'=>'<li><a href="">'.$tr->translate("GEP_REGISTER").'</a></li>',

						'studentstudy'=>'<li><a href="">'.$tr->translate("GEP_REGISTER").'</a></li>',
						//'gep'=>'<li><a href="">'.$tr->translate("GEP_REGISTER").'</a></li>',

						//'register'=>'<li><a href="">'.$tr->translate("KINDERGARTEN_REGISTER").'</a></li>',
						'studentgroup'=>'<li><a href="">'.$tr->translate("STUDENT_GROUP").'</a></li>',
						'studentchangegroup'=>'<li><a href="">'.$tr->translate("STUDENT_CHANGE_GROUP").'</a></li>',
						'groupstudentchangegroup'=>'<li><a href="">'.$tr->translate("GROUP_STUDENT_CHANGE_GROUP").'</a></li>',
						'studentdrop'=>'<li><a href="">'.$tr->translate("STUDENT_DROP").'</a></li>',
						'attendent'=>'<li><a href="">'.$tr->translate("ATTENDENT").'</a></li>',
						//'studentstudy'=>'<li><a href="">'.$tr->translate("STUDENT_STUDY").'</a></li>',
						//'student'=>'<li><a href="">'.$tr->translate("STUDENT_LIST").'</a></li>',
						'attendent'=>'<li><a href="">'.$tr->translate("ATTENDENT").'</a></li>',
						'language'=>'<li><a href="">'.$tr->translate("DEGREE_LANGUAGE").'</a></li>',
				
					//	'studentstudy'=>'<li><a href="">'.$tr->translate("STUDENT_STUDY").'</a></li>',
						/* 'certificate'=>'<li><a href="">'.$tr->translate("ALL_REPORT").'</a></li>',*/
				
				
				),
			'accounting'=>array(				
				'fee'=>'<li><a href="">'.$tr->translate("TUITION_FEE").'</a></li>',
				'servicecharge'=>'<li><a href="">'.$tr->translate("SERVICE_FEE").'</a></li>',
				'service'=>'<li><a href="">'.$tr->translate("SERVICE_NAME").'</a></li>',
				'services'=>'<li><a href="">'.$tr->translate("SERVICE_CATE").'</a></li>',
				//'Servicear'=>'<li><a href="">'.$tr->translate("SERVICE_INCOME").'</a></li>',
				'service'=>'<li><a href="">'.$tr->translate("SERVICES").'</a></li>',
				'services'=>'<li><a href="">'.$tr->translate("SERVICE_TYPE").'</a></li>',
				'bookanduniform'=>'<li><a href="">'.$tr->translate("BOOK_AND_UNIFORM").'</a></li>',
				'suspendservice'=>'<li><a href="">'.$tr->translate("STUDENT_SUSPEND_SERVICE").'</a></li>',
				/*'StudentDebt'=>'<li><a href="">'.$tr->translate("តារាងជំពាក់ជំពាក់").'</a></li>',
				'StudentLate'=>'<li><a href="">'.$tr->translate("STUDENT_LATE").'</a></li>',
				'Programcharge'=>'<li><a href="">'.$tr->translate("GEPPROGRAM_FEE").'</a></li>',
				'program'=>'<li><a href="">'.$tr->translate("SUBJECT").'</a></li>'
				'program'=>'<li><a href="">'.$tr->translate("Subjects").'</a></li>',*/
				'product'=>'<li><a href="">'.$tr->translate("PRODUCT").'</a></li>',
				'purchase'=>'<li><a href="">'.$tr->translate("PURCHASE").'</a></li>',
				'productcategory'=>'<li><a href="">'.$tr->translate("PRODUCT_CATEGORY").'</a></li>',
			    'exchangerate'=>'<li><a href="">'.$tr->translate("EXCHANGE_RATE_INFORMATION").'</a></li>',
				
			),
			
			'user'=>array(
				'index'=>'<li><a href="">'.$tr->translate("USER").'</a></li>',
			),	
			'rsvacl'=>array(
					 	'user'=>'<li><a href="">'.$tr->translate('USER').'</a></li>',
						'useraccess'=>'<li><a href="">'.$tr->translate("USER_ACCESS").'</a></li>',
					    'acl'=>'<li><a href="">'.$tr->translate("ACL").'</a></li>',
						'usertype'=>'<li><a href="">'.$tr->translate("USER_TYPE").'</a></li>',
				),
			'backup'=>array(
						'index'=>'<li><a href="">'.$tr->translate("Backup List").'</a></li>',
				),
			'allreport'=>array(
				'allstudent'=>"<li><span class''><a href=".$allstudent.">".$tr->translate("ALL_STUDENT_REPORT")."</a></span></li>",
				//'registra'=>"<li><span class''><a href=".$registrar.">".$tr->translate("REGISTRATION_REPORT")."</a></span></li>",
				//'fundation'=>"<li><span class''><a href=".$fundation.">".$tr->translate("ADMINISTRATION_REPORT")."</a></span></li>",
				'accounting'=>"<li><span class''><a href=".$accoutning.">".$tr->translate("ACCOUNTING_REPORT")."</a></span></li>",
				//'other'=>"<li><span class''><a href=".$other.">".$tr->translate("OTHER_REPORT")."</a></span></li>",
				//'rpt-student-list'=>"<li><span class''><a href='".$baseurl."/allreport/foundation/rpt-student-list'>".$tr->translate("STUDENT_LIST")."</a></span></li>",
				//'rpt-student-info'=>"<li><span class''><a href='".$baseurl."/allreport/foundation/rpt-student-info'>".$tr->translate("STUDENT_INFOMATION")."</a></span></li>",
				//'poc'=>"<li><a href='".$baseurl."/allreport/foundation/rpt-exam-degree'>".$tr->translate('STUDENT_EXAM_LIST')."</a></li>",
				/*'legal-document'=>"<li><a href='".$baseurl."/allreport/foundation/rpt-final-exams'>".$tr->translate("STUDENT_PASS_EXAM")."</a></li>",
				'rfm'=>"<li><a href='".$baseurl."/allreport/foundation/rpt-stuid'>".$tr->translate('STUDENT_CARD')."</a></li>",
				'pam'=>"<li><a href='".$baseurl."/allreport/foundation/rpt-foundation'>".$tr->translate("សិស្សបានធ្វើកាតរ")."</a></li>",
				'prc'=>"<li><a href='".$baseurl."/allreport/foundation/rpt-drop-out'>".$tr->translate("STUDENT_ADMISSION_EXAM")."</a></li>",
				'budget-regulation'=>"<li><a href='".$baseurl."/allreport/foundation/rpt-total-attendance'>".$tr->translate("TOTAL_ATTENDANT_LIST")."</a></li>",
				'da'=>"<li><a href='".$baseurl."/allreport/foundation/rpt-scorelist'>".$tr->translate("TEACHER_SCORE_LIST")."</a></li>",
				'asd'=>"<li><a href='".$baseurl."/allreport/foundation/rpt-student-attendance'>".$tr->translate("ATTENDANT_LIST")."</a></li>",
				*///'asdf'=>"<li><a href='".$baseurl."/allreport/foundation/rpt-amount-student'>".$tr->translate("ALL_STUDENT_LIST")."</a></li>",
				//''=>"<li><a href='".$baseurl."/allreport/foundation/rpt-scorelist'>".$tr->translate("REF_SOP")."</a></li>",
				//'rpt-allresult'=>"<li><a href='".$baseurl."/allreport/foundation/rpt-allresult'>".$tr->translate("YAER_END_EXAM_RESULT")."</a></li>",
				//''=>"<li><a href='".$baseurl."/allreport/foundation/rpt-certificate'>".$tr->translate("ឆ្នាំសិក្សាមូលដ្ឋាន ")."</a></li>",
				//'asasfd'=>"<li><a href='".$baseurl."/allreport/foundation/rpt-full-result'>".$tr->translate("ប្រាក់ចំណូលរបស់សិស្ស")."</a></li>",
				//'rpt-daily'=>"<li><a href='".$baseurl."/allreport/receiptionist/rpt-daily'>".$tr->translate("ប្រាក់ចំណូលរបស់និ")."</a></li>",
				//accounting
				//'rpt-account-rec'=>"<li><a href='".$baseurl."/allreport/accounting/rpt-account-rec'>".$tr->translate("ប្រាក់ចំណូលរបស់និ")."</a></li>",
				//'rpt-gep-fee'=>"<li><a href='".$baseurl."/allreport/accounting/rpt-gep-fee'>".$tr->translate("ប្រាក់ចំណូលរបស់និ")."</a></li>",
				//'rpt-gep-list'=>"<li><a href='".$baseurl."/allreport/accounting/rpt-gep-list'>".$tr->translate("ប្រាក់ចំណូលរបស់និ")."</a></li>",
				//'rpt-invoice'=>"<li><a href='".$baseurl."/allreport/accounting/rpt-invoice'>".$tr->translate("ប្រាក់ចំណូលរបស់និ")."</a></li>",
				//'rpt-list-of-item'=>"<li><a href='".$baseurl."/allreport/accounting/rpt-list-of-item'>".$tr->translate("ប្រាក់ចំណូលរបស់និ")."</a></li>",
				//'rpt-student-list-detail-part1'=>"<li><a href='".$baseurl."/allreport/accounting/rpt-student-list-detail-part1'>".$tr->translate("ប្រាក់ចំណូលរបស់និ")."</a></li>",
				//'rpt-student-list-detail-part2'=>"<li><a href='".$baseurl."/allreport/accounting/rpt-student-list-detail-part2'>".$tr->translate("ប្រាក់ចំណូលរបស់និ")."</a></li>",
				//'rpt-student-list-detail-part3'=>"<li><a href='".$baseurl."/allreport/accounting/rpt-student-list-detail-part3'>".$tr->translate("ប្រាក់ចំណូលរបស់និ")."</a></li>",
				//'rpt-studentpayment'=>"<li><a href='".$baseurl."/allreport/accounting/rpt-studentpayment'>".$tr->translate("ប្រាក់ចំណូលរបស់និ")."</a></li>",
				//'rpt-tuition-fee'=>"<li><a href='".$baseurl."/allreport/accounting/rpt-tuition-fee'>".$tr->translate("ប្រាក់ចំណូលរបស់និ")."</a></li>",
			),	
			'setting'=>array(
				'label'=>'<li><a href="">'.$tr->translate("Label_SETTING").'</a></li>',
				//'profile'=>'<li><a href="">'.$tr->translate("COM_PROFILE").'</a></li>',
				'database'=>'<li><a href="">'.$tr->translate("DATA_BASE_SETTING").'</a></li>',
				'setting'=>'<li><a href="">'.$tr->translate("System_SETTING").'</a></li>',			
				)
		); 
	?>
	<div id="header-left">
	<ul>
			<?php 
// 				$request=Zend_Controller_Front::getInstance()->getRequest();
				$dc=new Application_Model_Decorator();					
				$class="current-left";					
				$menu=$dc->getMenuLeft($arr_param_menu[$request->getModuleName()],$request->getControllerName(),$request->getModuleName());
				if($menu) echo $menu;					
			?>
	</ul>																
	</div>