<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('Report Student Change Group'); 
	echo $this->headTitle(''); 
	$frm =  $this->form_search;
?>	
<style>
tr td table tr th:{padding: 5px;margin: 5px;};

</style>
<div style="width: 29cm;margin: 0 auto;">
<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'foundation','action'=>'rpt-student-change-group')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<table width="80%">
	       <tr>
	           <td><?php echo $frm->getElement("title");?></td>
	           <td> <?php echo $frm->getElement("study_year");?></td>
	           <td> <?php echo $frm->getElement("grade_bac");?></td>
			   <td> <?php echo $frm->getElement("session");?></td>
			   <td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
	       </tr>
	</table>
	
</form>		
</div>
<div style="border: 1px dotted #000;background: #fff;width: 28cm; margin: 0 auto;min-height: 27cm;padding: 0.5cm;">
		<div id="divPrint">
		
							<table style="background:#fff; margin: 0 auto; width: 100%;">
								<tr>
									<td  width="28%">
										<img style="width:155px;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br /><br />
									</td>
									<td width="44%" align="center">
										<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">របាយការណ៏សិស្សប្តូរក្រុម</strong><br /><br >
									</td>
									<td width="28%" align="right">
									</td>
								</tr>
<style>
	table tr th{
		border: 1px solid #000;	
	}
	
</style>
								<tr>
									<td colspan="3">
										<table style="margin:0 auto;width:100%; border-collapse: collapse;white-space: nowrap;border: 1px solid #000;"  border="1" >
											<tr style="font-size:11px; height: 20px;" align="center" >
												<th rowspan="2">No.</th>
 												<th rowspan="2">Student ID</th>
												<th rowspan="2">Student Name</th>
												<th rowspan="2">Gender</th>
												<th colspan="6">From Group</th>
												<th colspan="6">To Group</th>
												<th rowspan="2">Moving Date</th>
												<th rowspan="2">Note</th>
												
											</tr>
											<tr style="font-size:10px; height: 20px;" align="center">
												<th >Code</th>
												<th >Academic</th>
												<th >Grade</th>
												<th >Room</th>
												<th >Semester</th>
												<th >Session</th>
												
											
												<th >Code</th>
												<th >Academic</th>
												<th >Grade</th>
												<th >Room</th>
												<th >Semester</th>
												<th >Session</th>
												
												<!--<th >Start Date</th>-->
												<!--<th >Amount Month</th>-->
												<!--<th >Expired Date</th>-->
											</tr>
										<?php $i=0; foreach ($this->rs AS $row) { $i++;?>
											<tr cellpadding="5"​ style="font-size:11px; height: 30px;" align="center" >
												<th ><?php echo $i;?></th>
												<th ><?php echo $row['stu_code'];?></th>
												<th align="left">&nbsp;&nbsp;<?php echo $row['name'];?>&nbsp;</th>	
												<th ><?php echo $row['sex'];?></th>
												
												<th ><?php echo $row['code'];?></th>
												<th >&nbsp;<?php echo $row['academic'];?>&nbsp;</th>
												<th align="left">&nbsp;<?php echo $row['grade'];?>&nbsp;</th>
												<th align="left">&nbsp;<?php echo $row['room_name'];?>&nbsp;</th>
												<th ><?php echo $row['semester'];?></th>
												<th >&nbsp;<?php echo $row['session'];?>&nbsp;</th>
												
												<th ><?php echo $row['to_code'];?></th>
												<th >&nbsp;<?php echo $row['to_academic'];?>&nbsp;</th>
												<th align="left">&nbsp;<?php echo $row['to_grade'];?>&nbsp;</th>
												<th align="left">&nbsp;<?php echo $row['to_room_name'];?>&nbsp;</th>
												<th ><?php echo $row['to_semester'];?></th>
												<th ><?php echo $row['to_session'];?></th>
												
												<!--  <th ><?php //echo date("d-M-Y",strtotime($row['start_date']));?></th> -->
												<!-- <th ><?php //echo $row['amount_month'];?></th> -->
												<!-- <th ><?php //echo $row['expired_date'];?></th> -->
												
												
												<th ><?php echo date("d-M-Y",strtotime($row['moving_date']));?></th>
												<th align="left">&nbsp;<?php echo $row['note'];?>&nbsp;</th>
												<!-- <th ><?php //echo $row['status'];?></th> -->
											</tr>
										<?php }?>	
										</table>	
									</td>
								</tr>
								<tr>
									<td colspan="3">&nbsp;</td>
								</tr>
								<tr>
									<td colspan="3">&nbsp;</td>
								</tr>
								<tr >
									<td align="center" width="25%">
										<span style="font-weight: bold;font-size: 14px;">Verified by</span>
									</td>
									<td  width="50%">
										&nbsp;
									</td>
									<td align="center"  width="25%">
										<span style="font-weight: bold;font-size: 14px;text-align: right;">Prepared by</span>
									</td>
								</tr>
							</table>
			
		</div>		
</div>