<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('Report Student Group'); 
	echo $this->headTitle(''); 
  //print_r($this->row_sub);exit();
	
	$parent=new Allreport_Model_DbTable_DbRptStudentScore();
	
	
?>	
<div style="width: 28cm;margin: 0 auto;">
<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'foundation','action'=>'rpt-group')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<input dojoType="dijit.form.TextBox"   id="txtsearch" name="txtsearch" placeholder="Search....." value="<?php echo $this->search['txtsearch'];?>" type="text">
		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
</form>
</div>
	<div style="border: 1px dotted #000;background: #fff;width: 27cm;margin: 0 auto;min-height: 27cm;padding: 0.5cm;">
		<div id="divPrint">
							<table style="background:#fff; margin: 0 auto; width: 100%;">
								<tr>
									<td width="28%" >
										<img style="width: 165px;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br /><br />
									</td>
									<td width="44%" align="center">
											<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 11px;font-family:'Khmer MEF2';">របាយការណ៏  ពិន្ទុសិស្ស</strong><br />
											<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 11px;font-family:'Khmer MEF2';">កម្រិត <?php //echo $this->row_group['degree'];?> <?php //echo $this->row_group['grade'];?> វេនសិក្សា <?php //echo $this->row_group['session'];?> ឆមាសទី  <?php //echo $this->row_group['semester'];?> </strong><br />
											<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 11px;font-family:'Khmer MEF2';">ឆ្នាំសិក្សា  <?php //echo $this->row_group['academic_year'];?> លេខកូដក្រុម <?php //echo $this->row_group['group_code'];?> បន្ទប់ <?php //echo $rs['room_name'];?> </strong><br />
												 
									</td>
									<td width="28%" align="right">
									</td>
								</tr>
<style>
	table tr th{
		border: 1px solid #000;	
	}
</style>
								<tr>
									<td colspan="3">
										<table cellpadding="3"​ style="margin:0 auto;width:100%; border-collapse: collapse;white-space: nowrap;"  border="1" >
									<?php
										$old_group = '';$old_subject='';
										print_r($this->row_group);
									if(!empty($this->row_group)) foreach ($this->row_group As $key => $rs){?>
										  <?php if($old_group!=$rs['group_code']){?>

										  <?php if($key>0){?>
										  </table><br />
										  <table cellpadding="3"​ style="margin:0 auto;width:100%; border-collapse: collapse;white-space: nowrap;"  border="1" >
										 <?php }?> 
										  
										   <tr>
											   <td colspan="2">
											   	<span style="font-size: 15px;font-weight: bold;">Academic Year &nbsp;<?php echo $rs['academic_year'];?>&nbsp;Generation&nbsp; <?php echo $rs['session'];?></span>
											   </td>
											   <td>Group:<?php echo $rs['group_code'];?></td>
											   <td width="44%" align="center">
										    	 <strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 11px;font-family:'Khmer MEF2';">របាយការណ៏  ពិន្ទុសិស្ស</strong><br />
											     <strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 11px;font-family:'Khmer MEF2';">កម្រិត <?php //echo $this->row_group['degree'];?> <?php //echo $this->row_group['grade'];?> វេនសិក្សា <?php //echo $this->row_group['session'];?> ឆមាសទី  <?php //echo $this->row_group['semester'];?> </strong><br />
											     <strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 11px;font-family:'Khmer MEF2';">ឆ្នាំសិក្សា  <?php //echo $this->row_group['academic_year'];?> លេខកូដក្រុម <?php //echo $this->row_group['group_code'];?> បន្ទប់ <?php //echo $rs['room_name'];?> </strong><br />
									          </td>
										  </tr>
										  
										  <?php }else{ ?>
										  <?php }?>
										  
										   <?php if($old_subject!=$rs['subject_id']){?>
										   <?php if($key>0){?>
											  </table><br />
											  <table cellpadding="3"​ style="margin:0 auto;width:100%; border-collapse: collapse;white-space: nowrap;"  border="1" >
										 <?php }?>
										   
										   <tr>
											   <td colspan="3">&nbsp;&nbsp;Subject Name:<?php echo $rs['subject_name'];?></td>
											   <?php 
												$itemrs = $parent->getSubjectItem($rs['subject_id'],$rs['group_id']);
												if(!empty($itemrs)) foreach ($itemrs as $index =>$rsitem){
											  ?>
												<th><?php echo $rsitem['subject_name'];?></th>
												<?php }?>
										  </tr>
										  <?php }?>
											
											<tr style="font-size:11px; height: 20px;" align="center" >
												<th>No.</th>
												<th><?php echo $rs['stu_code'];?></th>
												<th><?php echo $rs['stu_enname'];?></th>
												<?php 
													$itemrs = $parent->getSubjectItem($rs['subject_id'],$rs['group_id']);
// 													print_r($itemrs);exit();
													if(!empty($itemrs)) foreach ($itemrs as $index =>$rsitem){
												?>
												<th><?php echo $rs['total_score'.$index];?></th>
												<?php }?>
												
											</tr>
											<?php
											$old_group=$rs['group_code'];
											$old_subject=$rs['subject_id'];
									}?>	 
										</table>	
									</td>
								</tr>
								
								
								
								
								<tr>
									<td colspan="3">&nbsp;</td>
								</tr>
								<tr>
									<td colspan="3">&nbsp;</td>
								</tr>
								<tr >
									<td align="center" width="25%">
										<span style="font-weight: bold;font-size: 14px;">Verified by</span>
									</td>
									<td  width="50%">
										&nbsp;
									</td>
									<td align="center"  width="25%">
										<span style="font-weight: bold;font-size: 14px;text-align: right;">Prepared by</span>
									</td>
								</tr>
							</table>
		</div>
	</div>