<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('Currency Smart | Transfer Report1 page'); 
	echo $this->headTitle();
	$base_url = Application_Form_FrmMessage::getUrl("/");
?>	
<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'foundation','action'=>'rpt-student-group')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<input dojoType="dijit.form.TextBox"   id="txtsearch" name="txtsearch" placeholder="Search by student name....." value="" type="text">
		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
</form>

<div style="border: 1px dotted #000;background: #fff;width: 26cm;margin: 0 auto;min-height: 27cm;">
		<div id="divPrint">
							<table style="background:#fff; margin: 0 auto; width: 100%;padding: 1cm; ">
								<tr style="font-size: 13px;">
										<td colspan="3" align="center">
											<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 11px;font-family:'Khmer MEF2';">ព្រះរាជាណាចក្រកម្ពុជា</strong><br />
											<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 11px;font-family:'Khmer MEF2';">ជាតិ សាសនា ព្រះមហាក្សត្រ</strong><br />
										</td>
									</tr>
									<tr>
										<td>&nbsp;</td>
									</tr>
									<tr>
										<td width="10%" >
											<img style="width: 155px;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br /><br />
										</td>
										<td align="center">
											<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 11px;font-family:'Khmer MEF2';">បញ្ជីរាយនាមសិស្ស</strong><br />
											<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 11px;font-family:'Khmer MEF2';">កម្រិត <?php echo $this->rr['degree'];?> <?php echo $this->rr['grade'];?> វេនសិក្សា <?php echo $this->rr['session'];?> ឆមាសទី  <?php echo $this->rr['semester'];?> </strong><br />
											<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 11px;font-family:'Khmer MEF2';">ឆ្នាំសិក្សា  <?php echo $this->rr['academic'];?> លេខកូដក្រុម <?php echo $this->rr['group_code'];?> បន្ទប់ <?php echo $this->rr['room_name'];?> </strong><br />
										</td>
										<td width="20%">
											<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 11px;font-family:'Khmer MEF2';">ក្រសួងអប់រំ យុវជន និងកីឡា</strong><br />
											<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 11px;font-family:'Khmer MEF2';margin-right: 25px;">សាលា អាស៊ាន ហ៊ែរីថេជ</strong><br /><br >
										</td>
									</tr>
									<tr>
										<td colspan="3">
											<table cellpadding="5"​ style="margin:0 auto;width:100%; border-collapse: collapse; white-space: nowrap;"  border="1" >
												<tr style="font-size:10px; height: 30px;" align="center" >
													<th rowspan="2">ល.រ</th>
													<th rowspan="2">អត្តលេខ</th>
													<th rowspan="2">គោលនាម-នាម</th>
													<th rowspan="2">អក្សរឡាតាំង</th>
													<th rowspan="2">ភេទ</th>
													<th rowspan="2">សញ្ជាតិ</th>
													<th rowspan="2">ថ្ងៃខែឆ្នាំកំណើត</th>	
													<th rowspan="2">កន្លែងកំណើត</th>
													<th rowspan="2">លេខទូរស័ព្ទ</th>					
													
												</tr>
												<tr></tr>
												<style> td{padding:0 3px; }</style>
												<?php  $i=0; foreach ($this->rs as $row){ $i++;?>
												<tr style="font-size:10px;height: 23px;"​ align="center">
													<td><?php echo $i;?></td>
													<td><?php echo $row['stu_code'];?></td>
													<td align="left"><?php echo $row['kh_name'];?></td>
													<td align="left"><?php echo $row['en_name'];?></td>
													<td><?php echo $row['sex'];?></td>
													<td><?php echo $row['nation'];?></td>
													<td><?php echo $row['dob'];?></td>
													<td><?php echo $row['pob'];?></td>
													<td><?php echo $row['tel'];?></td>
												</tr>
												<?php }?>	
											</table>	
										</td>
									</tr>
							</table>
		</div>
	</div>
