<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('Currency Smart | Transfer Report page'); 
	echo $this->headTitle('SRMS | Student Infomation'); 
	
?>
<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'foundation','action'=>'rpt-student-info')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<input dojoType="dijit.form.TextBox"   id="txtsearch" name="txtsearch" placeholder="Search by group code....." value="" type="text">
		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
</form>	
<div style="border: 1px dotted #000;background: #fff;">
		<div id="divPrint">
					<table style="background:#fff; margin: 0 auto; width: 100%;padding: 1cm; border:1px solid #000;" border="1">
							     <tr style="font-size: 13px;">
									<td colspan="3" align="center">
										<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">ព្រះរាជាណាចក្រកម្ពុជា</strong><br />
										<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">ជាតិ សាសនា ព្រះមហាក្សត្រ</strong><br />
									</td>
								</tr>
								<tr>
									  <td align="left" width="25%" >
											<img style="width: 155px;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br /><br />
									  </td>
									  <td align="center">
											<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">បញ្ជីពត៌មានសិស្ស</strong><br />
									   </td>
									   <td align="right" width="25%">
									   </td>
								</tr>
								<tr>
									<td colspan="3">
										<table cellpadding="5"​ style=" white-space:nowrap; margin:0 auto;width:100%; border-collapse: collapse; border: 1px solid #000;"  border="1" >
											<tr style="font-size:11px; background:#ccc; height: 15px;" align="center" >
												<th rowspan="2">&nbsp;No&nbsp;</th>
												<th rowspan="2">&nbsp;Student ID&nbsp;</th>	
												<th rowspan="2">&nbsp;Name&nbsp;</th>
												<th rowspan="2">&nbsp;English Name&nbsp;</th>
												<th rowspan="2">&nbsp;Gender&nbsp;</th>												
												<th rowspan="2">&nbsp;Nationality&nbsp;</th>
												<th rowspan="2">&nbsp;Date Of Birth&nbsp;</th>
												<th rowspan="2">&nbsp;Place Of Birth&nbsp;</th>
												<th colspan="3">&nbsp;Phone No&nbsp;</th>
												<th rowspan="2">&nbsp;Email&nbsp;</th>
												<th rowspan="2">&nbsp;Father's Khmer Name&nbsp;</th>
												<th rowspan="2">&nbsp;Father's English Name&nbsp;</th>
												<th rowspan="2">&nbsp;Nationality&nbsp;</th>
												<th rowspan="2">&nbsp;Occupation&nbsp;</th>
												<th rowspan="2">&nbsp;Mother's Khmer Name&nbsp;</th>
												<th rowspan="2">&nbsp;Mother's English Name&nbsp;</th>
												<th rowspan="2">&nbsp;Nationality&nbsp;</th>
												<th rowspan="2">&nbsp;Occupation&nbsp;</th>
												<th rowspan="2">&nbsp;Guardian Name&nbsp;</th>
												<th rowspan="2">&nbsp;Guardian Name&nbsp;</th>
												<th rowspan="2">&nbsp;Nationality&nbsp;</th>
												<th rowspan="2">&nbsp;Occupation&nbsp;</th>
												<th rowspan="2">&nbsp;Passport No&nbsp;</th>
												<th rowspan="2">&nbsp;Phone No&nbsp;</th>
												<th rowspan="2">&nbsp;Email&nbsp;</th>
												<th rowspan="2">&nbsp;Address&nbsp;</th>
												<th rowspan="2">&nbsp;Remark&nbsp;</th>
											</tr>
											<tr​​ style="font-size:11px; background:#ccc;" align="center" >
												<th style="font-size:11px; background:#ccc;"><small>&nbsp;Personal&nbsp;</small></th>
												<th style="font-size:11px; background:#ccc;"><small>&nbsp;Father&nbsp;</small></th>
												<th style="font-size:11px; background:#ccc;"><small>&nbsp;mother&nbsp;</small></th>
											</tr>
											<style> td{padding:0 1px; }</style>
											<?php  $i=0; foreach ($this->rs as $row){ $i++;?>
											<tr style="white-space:nowrap; font-size:10px; height:18px;"​ align="center">
												<td><?php echo $i;?></td>
												<td style="white-space: nowrap;"><?php echo $row['stu_code'];?></td>
												<td align="left" style="white-space: nowrap;"><?php echo $row['stu_khname'];?></td>
												<td align="left" style="white-space: nowrap;"><?php echo $row['stu_enname'];?></td>
												<td><?php echo $row['gender'];?></td>
												<td><?php echo $row['nationality'];?></td>
												<td><?php echo $row['dob'];?></td>
												<td><?php echo $row['address'];?></td>
												<td><?php echo $row['tel'];?></td>
												<td><?php echo $row['father_phone'];?></td>
												<td><?php echo $row['mother_phone'];?></td>
												<td><?php echo $row['email'];?></td>
												<td><?php echo $row['father_khname'];?></td>
												<td><?php echo $row['father_enname'];?></td>
												<td><?php echo $row['father_nation'];?></td>
												<td><?php echo $row['far_job'];?></td>
												<td><?php echo $row['mother_khname'];?></td>
												<td><?php echo $row['mother_enname'];?></td>
												<td><?php echo $row['mother_nation'];?></td>
												<td><?php echo $row['mom_job'];?></td>
												<td><?php echo $row['guardian_khname'];?></td>
												<td><?php echo $row['guardian_enname'];?></td>
												<td><?php echo $row['guardian_nation'];?></td>
												<td><?php echo $row['guardian_document'];?></td>
												<td><?php  echo $row['guar_job'];?></td>
												<td><?php echo $row['guardian_tel'];?></td>
												<td><?php echo $row['guardian_email'];?></td>
												<td ><?php echo $row['home_num'];?> <?php echo $row['street_num'];?> <?php echo $row['village_name'];?> <?php echo $row['commune_name'];?> <?php  echo $row['pro'];?></td>
												<td><?php echo $row['remark'];?></td>
											</tr>
											<?php }?>	
										</table>	
									</td>
								</tr>
							</table>
		</div>
	</div>
							