<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('Report Student Drop'); 
	echo $this->headTitle(''); 
	$frm =  $this->form_search;
?>	
<div style="width: 28cm;margin: 0 auto;">
<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'foundation','action'=>'rpt-student-drop')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		
		<table width="80%">
	       <tr>
	           <td><?php echo $frm->getElement("title");?></td>
	           <td> <?php echo $frm->getElement("study_year");?></td>
	           <td> <?php echo $frm->getElement("grade_bac");?></td>
			   <td> <?php echo $frm->getElement("session");?></td>
			   <td>
			   		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
	       	   </td>
	       </tr>
		</table>
		
		
</form>		
</div>
	<div style="border: 1px dotted #000;background: #fff;width: 27cm;margin: 0 auto;min-height: 27cm;padding: 0.5cm;">	
		<div id="divPrint">
							<table style="background:#fff; margin: 0 auto;width: 100%">
								<tr>
									<td width="28%" align="left">
										<img style="width: 70%;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br /><br />
									</td>
									<td  align="center">
										<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">របាយការណ៏  សិស្សឈប់សិក្សា</strong><br />
									</td>
									<td width="28%" align="right">
									</td>
								</tr>
							<style>
								table tr th{
									border: 1px solid #000;	
								}
							</style>
								<tr>
									<td colspan="3">
										<table cellpadding="5"​ style="margin:0 auto;width:100%; border-collapse: collapse;"  border="1" >
											<tr style="font-size:11px; height: 20px;" align="center" >
												<th >No.</th>
												<th >Student ID</th>
												<th >Student Name</th>
												<th >Gender</th>
												<th >AcademicYear</th>
												<th >Grade</th>
												<th >Session</th>
												<th >Type</th>
												<th >Date Stop</th>
												<th >Note</th>
												
											</tr>
										<?php $i=0; foreach ($this->rs AS $row) { $i++;?>
											<tr style="font-size:11px; height: 20px;" align="center" >
												<th ><?php echo $i;?></th>
												<th ><?php echo $row['stu_id'];?></th>
												<th align="left">&nbsp;&nbsp;<?php echo $row['name'];?></th>
												<th ><?php echo $row['sex'];?></th>
												<th ><?php echo $row['academic_year'];?></th>
												<th ><?php echo $row['grade'];?></th>
												<th ><?php echo $row['session'];?></th>
												<th ><?php echo $row['type'];?></th>
												<th ><?php echo $row['date'];?></th>
												<th ><?php echo $row['note'];?></th>
											</tr>
										<?php }?>	
										</table>	
									</td>
								</tr>
								<tr>
									<td colspan="3">&nbsp;</td>
								</tr>
								<tr>
									<td colspan="3">&nbsp;</td>
								</tr>
								<tr >
									<td align="center" width="25%">
										<span style="font-weight: bold;font-size: 14px;">Verified by</span>
									</td>
									<td  width="50%">
										&nbsp;
									</td>
									<td align="center"  width="25%">
										<span style="font-weight: bold;font-size: 14px;text-align: right;">Prepared by</span>
									</td>
								</tr>
							</table>
		</div>		
	</div>
