<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('Report Student Group'); 
	echo $this->headTitle(''); 
  //print_r($this->row_sub);exit();
	
?>	
<div style="width: 28cm;margin: 0 auto;">
<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'foundation','action'=>'rpt-group')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<input dojoType="dijit.form.TextBox"   id="txtsearch" name="txtsearch" placeholder="Search....." value="<?php echo $this->search['txtsearch'];?>" type="text">
		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
</form>
</div>
	<div style="border: 1px dotted #000;background: #fff;width: 27cm;margin: 0 auto;min-height: 27cm;padding: 0.5cm;">
		<div id="divPrint">
							<table style="background:#fff; margin: 0 auto; width: 100%;">
								<tr>
									<td width="28%" >
										<img style="width: 165px;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br /><br />
									</td>
									<td width="44%" align="center">
										<strong​​ style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">របាយការណ៏  ពិន្ទុសិស្ស</strong><br />
										<strong></strong><br />
									</td>
									<td width="28%" align="right">
									</td>
								</tr>
<style>
	table tr th{
		border: 1px solid #000;	
	}                       
</style>                <?php $aca =null; $gr = null; ?>
                        
								<tr>
									<td colspan="3">
										<table cellpadding="3"​ style="margin:0 auto;width:100%; border-collapse: collapse;white-space: nowrap;" border="1"  >
											<?php $st = null;  $i=0; $thead = 0; foreach($this->row_studet As $key=>$rs_stu){ echo $gr."=".$rs_stu["group_id"];?>
											<?php //if($aca!=$rs_stu["academic_id"]){?>
												<tr>
													<?php if($gr!=$rs_stu["group_id"]){ $thead=1;?>
														<td colspan="9"><?php echo $rs_stu["group_name"]?></td>
													<?php }else{$thead=0;}?>
												</tr>
											<?php $aca=$rs_stu["academic_id"];
											// }?>
											<?php if($thead!=0){?>
											<tr style="font-size:11px; height: 20px;" align="center" >
												<th>No.</th>
												<th>Studen No</th>
												<th>Students Name</th>
												<?php 
													if(!empty($this->row_sub)) foreach($this->row_sub As $rs_par){
														
												?>
												<?php if($rs_par["subject_id"]==$rs_stu["subject_id"]){?>
												<th><?php echo $rs_par['subject_name'];?></th>
												<?php }?>
												<?php }?>
												<th >Final Score</th>
												<th >Remarks</th>
												
											</tr>
											<?php }?>
											 <?php  
												if($st!=$rs_stu["stu_id"]){
													$i=$i+1;
											 	$old_stu = $rs_stu["stu_id"];
											?>
											<tr>
													<td><?php echo $i;?></td>
													<td><?php echo $rs_stu['stu_enname'];?></td>
													<td><?php echo $rs_stu['stu_code'];?></td>
													<?php foreach($this->row_sub As $rs_par){ $old_sub = $rs_par["subject_id"]?>
															<?php foreach ($this->row_studet As $rs_stus){?>
																<?php 
																	if($old_stu==$rs_stus["stu_id"]){
																	if($old_sub==$rs_stus["subject_id"]){
																?>
																<td><?php echo $rs_stus["score"]?></td>
																<?php } }?>
															<?php }?>
													<?php }?>
											</tr>
											
											<?php $st=$rs_stu["stu_id"]; } $gr=$rs_stu["group_id"];
											 }?>
										</table>	
									</td>
								</tr>
								
								<tr>
									<td colspan="3">&nbsp;</td>
								</tr>
								<tr>
									<td colspan="3">&nbsp;</td>
								</tr>
								<tr >
									<td align="center" width="25%">
										<span style="font-weight: bold;font-size: 14px;">Verified by</span>
									</td>
									<td  width="50%">
										&nbsp;
									</td>
									<td align="center"  width="25%">
										<span style="font-weight: bold;font-size: 14px;text-align: right;">Prepared by</span>
									</td>
								</tr>
							</table>
		</div>
	</div>