<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('Currency Smart | Transfer Report page'); 
	$this->headTitle('SRMS | Report Static Student By Year'); 
	echo $this->headTitle();
	$base_url = Application_Form_FrmMessage::getUrl("/");
?>	
<form  id='rpt_static_student' action="<?php echo $this->url(array('module'=>'foundation','controller'=>'report','action'=>'rpt-static-student')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<div style="width:100%; background:none repeat scroll 0% 0% rgba(234, 255, 253, 1);">
		<table width="100%" style="margin: 0 auto;">
			<tr>
				<td>
				<fieldset style="background: none;height: 600px;overflow: scroll;overflow-x:hidden;">
							<legend align="center" ><strong><?php echo $tr->translate("");?></strong></legend>
							
								<?php if(!empty($this->year)) foreach ($this->year as $year){?>
										<?php if(!empty($this->rs)) foreach ($this->rs as $rs){?>
										<?php 
											$OldYearID=$year['id'];
											$YearID=$rs['academic_year'];
											
											if($OldYearID==$YearID){
												
												echo $OldYearID ."=".$YearID;
												//echo $year['generation'];
										?>
							<table style="width:30cm;background:#fff; margin: 0 auto; border: 1px dotted #ccc;">
								<tr style="font-size: 18px;">
									<td colspan="2"></td>
									
									<td align="center">
										<strong>ស្ថិតិសិស្ស ជំនាន់ទី <span><?php echo $year['generation'];?></span> ឆ្នាំសិក្សា <span><?php echo $year['from_academic']?>-</span><?php echo $year['to_academic']?> ចុះឈ្មោះលើកទី <span> <?php echo $year['time']?></span></strong><br /><br />
									</td>
									
								</tr>
								<tr>
									<td colspan="4">
										<table cellpadding="5"​ style="margin:0 auto;width:100%; border-collapse: collapse;"  border="1" >
											<tr style="font-size:14px; height: 30px;" align="center" >
											<style> th{border-top:1px solid #000;}</style>
												<th rowspan="5" style="font-size: 20px;">
													<svg xmlns="http://www.w3.org/2000/svg" width="24" height="150">
													 <text transform="rotate(270, 12, 0) translate(-120,5)">Batch <?php echo $year['generation']?></text> 
													</svg>
												</th>
												<th>Session</th>
												<?php if(!empty($this->title)) foreach ($this->title as $header){?>
												<th><?php echo $header['major_enname']?></th>
												<?php }?>
											</tr>
											
											<?php 
												
													if(!empty($this->session)) foreach ($this->session as $session){?>
											<tr style="font-size:12px;border: 1px solid #000;"​ align="center">
												<th><?php echo $session['name_en'];?></th>
												<?php
													if(!empty($this->title)) foreach ($this->title as $header){ 
													$old_session =$session["key_code"];
													
													$old_grade =$header["major_id"];
													$count=0;
													//$total_grade = 0;
													foreach ($this->rs as $rs){
														//echo $old_session ."=".$rs["session"];
														//print_r($rs);
														$counts = count($rs["stu_id"]);
														//$total_grades = count($rs["stu_id"]);
														$sessions = $rs['session'];
														$grade = $rs["grade"];
														$stu_id=$rs['stu_id'];
														foreach ($this->year as $row){
															$old_stu_id=$row['stu_id'];
															
															if($old_session == $sessions){
																if($old_grade==$grade){
																	if($old_stu_id==$stu_id){
																		$count = $count+$counts;
																		//$total_grade = $total_grade+$total_grades;
																	}
																}
															}
														}
													}
													//echo $total_grade;
												?>
												<td><?php echo $count;?></td>
												<?php }?>
											</tr>
											<?php }?>
											
											<tr style="font-size:13px;border: 1px solid #000;"​ align="center">
												<th colspan="2">Total</th>
												<?php 
													if(!empty($this->title)) foreach ($this->title as $header){ 
														$old_grades =$header["major_id"];
														$total_grade = 0;
														$t_stus = 0;
														foreach ($this->rs as $rs){
															$t_stu = count($rs["stu_id"]);
															$t_stus = $t_stus+$t_stu;
															$total_grades = count($rs["stu_id"]);
															$greades = $rs["grade"];
															if($old_grades==$greades){
																$total_grade = $total_grade+$total_grades;
															}
														}
														
												?>
													<td><?php echo $total_grade;?></td>
												<?php }?>
											</tr>	
											
										</table>
										<br><br>	
									</td>
								</tr>
								<tr>
									<td colspan="3" align="left">
									<style>td{height:30px;}</style>
										<table cellpadding="5"​ style="margin:0 auto;width:20%; border-collapse: collapse;" align="left" >
										<tr style="font-size:14px;" align="center">
											
											<td>Grand Total:</td>
											<td bgcolor="#fc0"><?php echo $t_stus;?></td>
										
										</tr>
										</table>
									</td>
								</tr>
								<tr><td><br><br><br><br></td></tr>
								
							</table>
							<?php }?>
							<?php }?>
							<?php }?>
				</fieldset>		
				</td>
			</tr>
		</table>
	</div>	
</form>
