<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle('Report Student Change Group'); 
	echo $this->headTitle(''); 
	
?>	

<style>
tr td table tr th:{padding: 5px;margin: 5px;};

</style>
<form  id='foundation_class' action="<?php echo $this->url(array('module'=>'allreport','controller'=>'studentchangegroup','action'=>'rpt-student-change-group')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<select dojoType="dijit.form.FilteringSelect" name="searchby" id="searchby" placeholder="Search by ....." value="" type="text">
			<option value="0">All</option>
			<option value="1">Student ID</option>
			<option value="2">Student Name</option>
		</select>
		<input dojoType="dijit.form.TextBox" required="true"  id="txtsearch" name="txtsearch" placeholder="Search....." value="" type="text">
		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" name="search"  type="submit"><?php echo $tr->translate("SEARCH");?></button>
</form>		
<div style="border: 1px dotted #000;background: #fff;margin: 0 auto;min-height: 27cm;">
		<div id="divPrint">
		
							<table style="background:#fff; margin: 0 auto; width: 100%;padding: 1cm;">
								<tr style="font-size: 13px;">
									<td colspan="2"></td>
									<td align="right">
										<strong></strong><br />
										<strong></strong><br />
									</td>
								</tr>
								<tr>
									<td  width="28%">
										<img style="width:155px;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br /><br />
									</td>
									<td align="center">
										<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">របាយការណ៏សិស្សដែលបានប្តូរក្រុម</strong><br /><br >
									</td>
									<td width="28%" align="right">
										<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';">ក្រសួងអប់រំ យុវជន និងកីឡា</strong><br />
										<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';margin-right: 25px;">សាលា អាស៊ាន ហ៊ែរីថេជ</strong><br /><br >
									</td>
								</tr>
								<tr>
									<td colspan="3">
										<table style="margin:0 auto;width:100%; border-collapse: collapse;white-space: nowrap;border: 1px solid #000;"  border="1" >
											<tr style="font-size:11px; height: 30px;" align="center" >
												<th rowspan="2">ល.រ</th>
												<th rowspan="2">Student ID</th>
												<th rowspan="2">Student Name</th>
												<th rowspan="2">Gender</th>
												<th colspan="9">From Group</th>
												<th colspan="6">To Group</th>
												<th rowspan="2">Moving Date</th>
												<th rowspan="2">Note</th>
												
											</tr>
											<tr style="font-size:10px; height: 30px;" align="center">
												<th >Code</th>
												<th >Academic</th>
												<th >Grade</th>
												<th >Room</th>
												<th >Semester</th>
												<th >Session</th>
												<th >Start Date</th>
												<th >Amount Month</th>
												<th >Expired Date</th>
											
												<th >Code</th>
												<th >Academic</th>
												<th >Grade</th>
												<th >Room</th>
												<th >Semester</th>
												<th >Session</th>
												
												<!--<th >Start Date</th>-->
												<!--<th >Amount Month</th>-->
												<!--<th >Expired Date</th>-->
											</tr>
										<?php $i=0; foreach ($this->rs AS $row) { $i++;?>
											<tr style="font-size:11px; height: 30px;" align="center" >
												<th ><?php echo $i;?></th>
												<th ><?php echo $row['stu_id'];?></th>
												<th align="left"><?php echo $row['name'];?></th>	
												<th ><?php echo $row['sex'];?></th>
												
												<th ><?php echo $row['code'];?></th>
												<th ><?php echo $row['academic'];?></th>
												<th ><?php echo $row['grade'];?></th>
												<th ><?php echo $row['room_name'];?></th>
												<th ><?php echo $row['semester'];?></th>
												<th ><?php echo $row['session'];?></th>
												
												<th ><?php echo date("d-M-Y",strtotime($row['start_date']));?></th>
												<th ><?php echo $row['amount_month'];?></th>
												<th ><?php echo date("d-M-Y",strtotime($row['expired_date']));?></th>
												
												
												
												<th ><?php echo $row['to_code'];?></th>
												<th ><?php echo $row['to_academic'];?></th>
												<th ><?php echo $row['to_grade'];?></th>
												<th ><?php echo $row['to_room_name'];?></th>
												<th ><?php echo $row['to_semester'];?></th>
												<th ><?php echo $row['to_session'];?></th>
												
												<!--  <th ><?php //echo date("d-M-Y",strtotime($row['start_date']));?></th> -->
												<!-- <th ><?php //echo $row['amount_month'];?></th> -->
												<!-- <th ><?php //echo $row['expired_date'];?></th> -->
												
												
												<th ><?php echo date("d-M-Y",strtotime($row['moving_date']));?></th>
												<th align="left"><?php echo $row['note'];?></th>
												<!-- <th ><?php //echo $row['status'];?></th> -->
											</tr>
										<?php }?>	
										</table>	
									</td>
								</tr>
							</table>
			
		</div>		
</div>